import type { Location, InventoryItem, Quest } from "./types"

// Game world locations
export const WORLD_LOCATIONS: Location[] = [
  {
    id: "goldenheart-tavern",
    name: "Golden Heart Tavern",
    description: "A cozy tavern in the city center where adventurers gather",
    type: "town",
    connections: ["town-square", "market-district"],
    discovered: true,
    x: 300,
    y: 200,
  },
  {
    id: "town-square",
    name: "Town Square",
    description: "The central square of the city with a fountain and hero statue",
    type: "town",
    connections: ["goldenheart-tavern", "market-district", "temple", "north-gate"],
    discovered: true,
    x: 300,
    y: 150,
  },
  {
    id: "market-district",
    name: "Market District",
    description: "A bustling area with shops, stores, and merchants",
    type: "town",
    connections: ["town-square", "goldenheart-tavern"],
    discovered: true,
    x: 350,
    y: 180,
  },
  {
    id: "temple",
    name: "Temple of Light",
    description: "A magnificent temple with tall columns and stained glass",
    type: "landmark",
    connections: ["town-square"],
    discovered: false,
    x: 250,
    y: 120,
  },
  {
    id: "north-gate",
    name: "North Gate",
    description: "Massive gates leading to the northern lands",
    type: "town",
    connections: ["town-square", "dark-forest"],
    discovered: false,
    x: 300,
    y: 100,
  },
  {
    id: "dark-forest",
    name: "Dark Forest",
    description: "A gloomy forest full of dangers and secrets",
    type: "wilderness",
    connections: ["north-gate", "ancient-ruins"],
    discovered: false,
    x: 300,
    y: 50,
  },
  {
    id: "ancient-ruins",
    name: "Ancient Ruins",
    description: "Mysterious ruins of an ancient civilization",
    type: "dungeon",
    connections: ["dark-forest"],
    discovered: false,
    x: 250,
    y: 30,
  },
  {
    id: "goblin-cave",
    name: "Goblin Cave",
    description: "A dark cave where goblins dwell",
    type: "dungeon",
    connections: ["dark-forest"],
    discovered: false,
    x: 350,
    y: 30,
  },
]

// Enhanced starting items by class
export const STARTING_ITEMS: { [key: string]: InventoryItem[] } = {
  Fighter: [
    {
      id: "longsword",
      name: "Longsword",
      type: "weapon",
      description: "A quality battle sword with a sharp blade",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 3,
      stats: { damage: "1d8+STR" },
    },
    {
      id: "chain-mail",
      name: "Chain Mail",
      type: "armor",
      description: "Sturdy chain mail for protection in battle",
      quantity: 1,
      value: 75,
      rarity: "common",
      weight: 20,
      stats: { armor: 16 },
    },
    {
      id: "shield",
      name: "Shield",
      type: "armor",
      description: "A wooden shield with metal reinforcements",
      quantity: 1,
      value: 10,
      rarity: "common",
      weight: 6,
      stats: { armor: 2 },
    },
  ],
  Wizard: [
    {
      id: "quarterstaff",
      name: "Quarterstaff",
      type: "weapon",
      description: "A wooden staff for focusing magic and self-defense",
      quantity: 1,
      value: 2,
      rarity: "common",
      weight: 4,
      stats: { damage: "1d6" },
    },
    {
      id: "spellbook",
      name: "Spellbook",
      type: "tool",
      description: "A personal spellbook for a beginning wizard",
      quantity: 1,
      value: 50,
      rarity: "uncommon",
      weight: 3,
    },
    {
      id: "component-pouch",
      name: "Component Pouch",
      type: "tool",
      description: "A pouch with material components for spells",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 2,
    },
  ],
  Rogue: [
    {
      id: "shortsword",
      name: "Shortsword",
      type: "weapon",
      description: "A light and fast blade for sneak attacks",
      quantity: 1,
      value: 10,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d6+DEX" },
    },
    {
      id: "dagger-set",
      name: "Dagger Set",
      type: "weapon",
      description: "Two sharp daggers for throwing and melee combat",
      quantity: 2,
      value: 4,
      rarity: "common",
      weight: 1,
      stats: { damage: "1d4+DEX" },
    },
    {
      id: "thieves-tools",
      name: "Thieves' Tools",
      type: "tool",
      description: "Professional tools for picking locks",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 1,
    },
    {
      id: "leather-armor",
      name: "Leather Armor",
      type: "armor",
      description: "Light leather armor that doesn't hinder stealth",
      quantity: 1,
      value: 10,
      rarity: "common",
      weight: 10,
      stats: { armor: 11 },
    },
  ],
  Cleric: [
    {
      id: "war-hammer",
      name: "Warhammer",
      type: "weapon",
      description: "A sacred weapon for fighting evil",
      quantity: 1,
      value: 15,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d8+STR" },
    },
    {
      id: "holy-symbol",
      name: "Holy Symbol",
      type: "tool",
      description: "A symbol of your deity for performing miracles",
      quantity: 1,
      value: 5,
      rarity: "common",
      weight: 0,
    },
    {
      id: "scale-mail",
      name: "Scale Mail",
      type: "armor",
      description: "Armor made of metal scales",
      quantity: 1,
      value: 50,
      rarity: "common",
      weight: 45,
      stats: { armor: 14 },
    },
  ],
  Ranger: [
    {
      id: "longbow",
      name: "Longbow",
      type: "weapon",
      description: "A powerful bow for ranged attacks",
      quantity: 1,
      value: 50,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d8+DEX" },
    },
    {
      id: "arrows",
      name: "Arrows",
      type: "weapon",
      description: "A quiver with 30 arrows",
      quantity: 30,
      value: 1,
      rarity: "common",
      weight: 1,
    },
    {
      id: "scimitar",
      name: "Scimitar",
      type: "weapon",
      description: "A curved blade for melee combat",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 3,
      stats: { damage: "1d6+DEX" },
    },
  ],
  Barbarian: [
    {
      id: "greataxe",
      name: "Greataxe",
      type: "weapon",
      description: "A massive two-handed barbarian axe",
      quantity: 1,
      value: 30,
      rarity: "common",
      weight: 7,
      stats: { damage: "1d12+STR" },
    },
    {
      id: "handaxe-set",
      name: "Handaxes",
      type: "weapon",
      description: "Two handaxes for throwing",
      quantity: 2,
      value: 5,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d6+STR" },
    },
  ],
  Bard: [
    {
      id: "rapier",
      name: "Rapier",
      type: "weapon",
      description: "An elegant blade for fencing",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d8+DEX" },
    },
    {
      id: "lute",
      name: "Lute",
      type: "tool",
      description: "A musical instrument for spells",
      quantity: 1,
      value: 35,
      rarity: "common",
      weight: 2,
    },
  ],
  Paladin: [
    {
      id: "longsword-blessed",
      name: "Blessed Sword",
      type: "weapon",
      description: "A longsword consecrated with divine power",
      quantity: 1,
      value: 50,
      rarity: "uncommon",
      weight: 3,
      stats: { damage: "1d8+STR", bonus: "+1 vs evil" },
    },
    {
      id: "chain-mail-blessed",
      name: "Consecrated Chain Mail",
      type: "armor",
      description: "Chain mail blessed by a priest",
      quantity: 1,
      value: 100,
      rarity: "uncommon",
      weight: 20,
      stats: { armor: 16, bonus: "+1 vs evil" },
    },
  ],
}

// Common starting items (same for all)
export const COMMON_STARTING_ITEMS: InventoryItem[] = [
  {
    id: "health-potion",
    name: "Healing Potion",
    type: "consumable",
    description: "Restores 2d4+2 hit points",
    quantity: 2,
    value: 50,
    rarity: "common",
    weight: 0.5,
  },
  {
    id: "rations",
    name: "Trail Rations",
    type: "consumable",
    description: "Nutritious food for one day",
    quantity: 5,
    value: 2,
    rarity: "common",
    weight: 2,
  },
  {
    id: "rope",
    name: "Rope (50 feet)",
    type: "tool",
    description: "Strong hemp rope",
    quantity: 1,
    value: 2,
    rarity: "common",
    weight: 10,
  },
  {
    id: "torch",
    name: "Torch",
    type: "tool",
    description: "Illuminates darkness for 6 hours",
    quantity: 3,
    value: 1,
    rarity: "common",
    weight: 1,
  },
]

// Starting quests
export const STARTING_QUESTS: Quest[] = [
  {
    id: "welcome-quest",
    title: "Welcome, Adventurer!",
    description: "Get familiar with the city and its inhabitants",
    status: "active",
    objectives: [
      {
        id: "visit-tavern",
        description: "Visit the Golden Heart Tavern",
        completed: true,
      },
      {
        id: "talk-to-merchant",
        description: "Talk to a merchant in the market",
        completed: false,
      },
      {
        id: "explore-temple",
        description: "Explore the Temple of Light",
        completed: false,
      },
    ],
    reward: {
      gold: 50,
      experience: 100,
    },
    giver: "Innkeeper",
    location: "goldenheart-tavern",
    createdAt: new Date(),
  },
]
