import type { Location, InventoryItem, Quest } from "./types"

// Локации игрового мира
export const WORLD_LOCATIONS: Location[] = [
  {
    id: "goldenheart-tavern",
    name: "Таверна 'Золотое Сердце'",
    description: "Уютная таверна в центре города, где собираются авантюристы",
    type: "town",
    connections: ["town-square", "market-district"],
    discovered: true,
    x: 300,
    y: 200,
  },
  {
    id: "town-square",
    name: "Городская площадь",
    description: "Центральная площадь города с фонтаном и статуей героя",
    type: "town",
    connections: ["goldenheart-tavern", "market-district", "temple", "north-gate"],
    discovered: true,
    x: 300,
    y: 150,
  },
  {
    id: "market-district",
    name: "Торговый квартал",
    description: "Шумный район с лавками, магазинами и торговцами",
    type: "town",
    connections: ["town-square", "goldenheart-tavern"],
    discovered: true,
    x: 350,
    y: 180,
  },
  {
    id: "temple",
    name: "Храм Света",
    description: "Величественный храм с высокими колоннами и витражами",
    type: "landmark",
    connections: ["town-square"],
    discovered: false,
    x: 250,
    y: 120,
  },
  {
    id: "north-gate",
    name: "Северные ворота",
    description: "Массивные ворота, ведущие к северным землям",
    type: "town",
    connections: ["town-square", "dark-forest"],
    discovered: false,
    x: 300,
    y: 100,
  },
  {
    id: "dark-forest",
    name: "Темный лес",
    description: "Мрачный лес, полный опасностей и тайн",
    type: "wilderness",
    connections: ["north-gate", "ancient-ruins"],
    discovered: false,
    x: 300,
    y: 50,
  },
  {
    id: "ancient-ruins",
    name: "Древние руины",
    description: "Загадочные руины древней цивилизации",
    type: "dungeon",
    connections: ["dark-forest"],
    discovered: false,
    x: 250,
    y: 30,
  },
  {
    id: "goblin-cave",
    name: "Пещера гоблинов",
    description: "Темная пещера, где обитают гоблины",
    type: "dungeon",
    connections: ["dark-forest"],
    discovered: false,
    x: 350,
    y: 30,
  },
]

// Улучшенные стартовые предметы по классам
export const STARTING_ITEMS: { [key: string]: InventoryItem[] } = {
  Fighter: [
    {
      id: "longsword",
      name: "Длинный меч",
      type: "weapon",
      description: "Качественный боевой меч с острым лезвием",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 3,
      stats: { damage: "1d8+STR" },
    },
    {
      id: "chain-mail",
      name: "Кольчуга",
      type: "armor",
      description: "Прочная кольчуга для защиты в бою",
      quantity: 1,
      value: 75,
      rarity: "common",
      weight: 20,
      stats: { armor: 16 },
    },
    {
      id: "shield",
      name: "Щит",
      type: "armor",
      description: "Деревянный щит с металлическими накладками",
      quantity: 1,
      value: 10,
      rarity: "common",
      weight: 6,
      stats: { armor: 2 },
    },
  ],
  Wizard: [
    {
      id: "quarterstaff",
      name: "Боевой посох",
      type: "weapon",
      description: "Деревянный посох для фокусировки магии и самозащиты",
      quantity: 1,
      value: 2,
      rarity: "common",
      weight: 4,
      stats: { damage: "1d6" },
    },
    {
      id: "spellbook",
      name: "Книга заклинаний",
      type: "tool",
      description: "Личная книга заклинаний начинающего мага",
      quantity: 1,
      value: 50,
      rarity: "uncommon",
      weight: 3,
    },
    {
      id: "component-pouch",
      name: "Мешочек компонентов",
      type: "tool",
      description: "Мешочек с материальными компонентами для заклинаний",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 2,
    },
  ],
  Rogue: [
    {
      id: "shortsword",
      name: "Короткий меч",
      type: "weapon",
      description: "Легкий и быстрый клинок для скрытых атак",
      quantity: 1,
      value: 10,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d6+DEX" },
    },
    {
      id: "dagger-set",
      name: "Набор кинжалов",
      type: "weapon",
      description: "Два острых кинжала для метания и ближнего боя",
      quantity: 2,
      value: 4,
      rarity: "common",
      weight: 1,
      stats: { damage: "1d4+DEX" },
    },
    {
      id: "thieves-tools",
      name: "Воровские инструменты",
      type: "tool",
      description: "Профессиональный набор для взлома замков",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 1,
    },
    {
      id: "leather-armor",
      name: "Кожаная броня",
      type: "armor",
      description: "Легкая кожаная броня, не мешающая скрытности",
      quantity: 1,
      value: 10,
      rarity: "common",
      weight: 10,
      stats: { armor: 11 },
    },
  ],
  Cleric: [
    {
      id: "war-hammer",
      name: "Боевой молот",
      type: "weapon",
      description: "Священное оружие для борьбы со злом",
      quantity: 1,
      value: 15,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d8+STR" },
    },
    {
      id: "holy-symbol",
      name: "Священный символ",
      type: "tool",
      description: "Символ божества для сотворения чудес",
      quantity: 1,
      value: 5,
      rarity: "common",
      weight: 0,
    },
    {
      id: "scale-mail",
      name: "Чешуйчатая броня",
      type: "armor",
      description: "Броня из металлических чешуек",
      quantity: 1,
      value: 50,
      rarity: "common",
      weight: 45,
      stats: { armor: 14 },
    },
  ],
  Ranger: [
    {
      id: "longbow",
      name: "Длинный лук",
      type: "weapon",
      description: "Мощный лук для дальних атак",
      quantity: 1,
      value: 50,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d8+DEX" },
    },
    {
      id: "arrows",
      name: "Стрелы",
      type: "weapon",
      description: "Колчан с 30 стрелами",
      quantity: 30,
      value: 1,
      rarity: "common",
      weight: 1,
    },
    {
      id: "scimitar",
      name: "Скимитар",
      type: "weapon",
      description: "Изогнутый клинок для ближнего боя",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 3,
      stats: { damage: "1d6+DEX" },
    },
  ],
  Barbarian: [
    {
      id: "greataxe",
      name: "Большой топор",
      type: "weapon",
      description: "Массивный двуручный топор варвара",
      quantity: 1,
      value: 30,
      rarity: "common",
      weight: 7,
      stats: { damage: "1d12+STR" },
    },
    {
      id: "handaxe-set",
      name: "Ручные топоры",
      type: "weapon",
      description: "Два ручных топора для метания",
      quantity: 2,
      value: 5,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d6+STR" },
    },
  ],
  Bard: [
    {
      id: "rapier",
      name: "Рапира",
      type: "weapon",
      description: "Элегантный клинок для фехтования",
      quantity: 1,
      value: 25,
      rarity: "common",
      weight: 2,
      stats: { damage: "1d8+DEX" },
    },
    {
      id: "lute",
      name: "Лютня",
      type: "tool",
      description: "Музыкальный инструмент для заклинаний",
      quantity: 1,
      value: 35,
      rarity: "common",
      weight: 2,
    },
  ],
  Paladin: [
    {
      id: "longsword-blessed",
      name: "Благословенный меч",
      type: "weapon",
      description: "Длинный меч, освященный божественной силой",
      quantity: 1,
      value: 50,
      rarity: "uncommon",
      weight: 3,
      stats: { damage: "1d8+STR", bonus: "+1 против зла" },
    },
    {
      id: "chain-mail-blessed",
      name: "Освященная кольчуга",
      type: "armor",
      description: "Кольчуга, благословенная священником",
      quantity: 1,
      value: 100,
      rarity: "uncommon",
      weight: 20,
      stats: { armor: 16, bonus: "+1 против зла" },
    },
  ],
}

// Общие стартовые предметы (одинаковые для всех)
export const COMMON_STARTING_ITEMS: InventoryItem[] = [
  {
    id: "health-potion",
    name: "Зелье лечения",
    type: "consumable",
    description: "Восстанавливает 2d4+2 очков здоровья",
    quantity: 2,
    value: 50,
    rarity: "common",
    weight: 0.5,
  },
  {
    id: "rations",
    name: "Дорожный паек",
    type: "consumable",
    description: "Питательная еда на один день",
    quantity: 5,
    value: 2,
    rarity: "common",
    weight: 2,
  },
  {
    id: "rope",
    name: "Веревка (15 метров)",
    type: "tool",
    description: "Прочная пеньковая веревка",
    quantity: 1,
    value: 2,
    rarity: "common",
    weight: 10,
  },
  {
    id: "torch",
    name: "Факел",
    type: "tool",
    description: "Освещает темноту на 6 часов",
    quantity: 3,
    value: 1,
    rarity: "common",
    weight: 1,
  },
]

// Стартовые квесты
export const STARTING_QUESTS: Quest[] = [
  {
    id: "welcome-quest",
    title: "Добро пожаловать, авантюрист!",
    description: "Познакомься с городом и его жителями",
    status: "active",
    objectives: [
      {
        id: "visit-tavern",
        description: "Посетить таверну 'Золотое Сердце'",
        completed: true,
      },
      {
        id: "talk-to-merchant",
        description: "Поговорить с торговцем на рынке",
        completed: false,
      },
      {
        id: "explore-temple",
        description: "Исследовать храм Света",
        completed: false,
      },
    ],
    reward: {
      gold: 50,
      experience: 100,
    },
    giver: "Трактирщик",
    location: "goldenheart-tavern",
    createdAt: new Date(),
  },
]
